/**
 * Dynamic Unit System and Distance Formatting Utilities for DriveCare.
 * Accommodates Metric (Canada / km) and Imperial (USA / mi) systems.
 */

export function getDistanceUnit(pref: 'imperial' | 'metric'): string {
  return 'km';
}

export function getDistanceLabel(pref: 'imperial' | 'metric'): string {
  return 'kilometers';
}

export function formatDistance(val: number, pref: 'imperial' | 'metric'): string {
  return `${val.toLocaleString()} km`;
}

/**
 * Cleanly swaps matching 'miles' substrings generated by core system schemas.
 * Support Traditional Chinese translations with advanced regex pattern reconstruction.
 */
export function localizeServerText(
  text: string, 
  pref: 'imperial' | 'metric', 
  lang: 'en' | 'zh-TW' = 'en'
): string {
  const unit = 'km';

  if (lang === 'zh-TW') {
    // 1. "Exceeded target of [target] miles (current: [current])"
    let match = text.match(/Exceeded target of ([\d,]+) miles \(current: ([\d,]+)\)/i);
    if (!match) {
      match = text.match(/Exceeded target of ([\d,]+) km \(current: ([\d,]+)\)/i);
    }
    if (match) {
      const targetVal = match[1];
      const currentVal = match[2];
      return `已超過目標里程 ${targetVal} ${unit} (當前實際里程：${currentVal} ${unit})`;
    }

    // 2. "Due soon! Only [diff] miles remaining of [target] target"
    match = text.match(/Due soon! Only ([\d,]+) miles remaining of ([\d,]+) target/i);
    if (!match) {
      match = text.match(/Due soon! Only ([\d,]+) km remaining of ([\d,]+) target/i);
    }
    if (match) {
      const diffVal = match[1];
      const targetVal = match[2];
      return `即將到期！距離目標 ${targetVal} ${unit} 僅剩最後 ${diffVal} ${unit}`;
    }

    // 3. "Safe: [diff] miles remaining of [target] target"
    match = text.match(/Safe: ([\d,]+) miles remaining of ([\d,]+) target/i);
    if (match) {
      const diffVal = match[1];
      const targetVal = match[2];
      return `安全運作中：距離目標 ${targetVal} ${unit} 還剩 ${diffVal} ${unit}`;
    }

    // 4. "Overdue since [date] ([days] days ago)"
    match = text.match(/Overdue since ([\d-\/]+) \((\d+) days ago\)/i);
    if (match) {
      const dateVal = match[1];
      const daysVal = match[2];
      return `自 ${dateVal} 起已逾期 (${daysVal} 天前)`;
    }

    // 5. "Due in [days] days ([date])"
    match = text.match(/Due in (\d+) days \(([\d-\/]+)\)/i);
    if (match) {
      const daysVal = match[1];
      const dateVal = match[2];
      return `將在 ${daysVal} 天後到期 (${dateVal})`;
    }

    // 6. "Upcoming on [date] ([days] days left)"
    match = text.match(/Upcoming on ([\d-\/]+) \((\d+) days left\)/i);
    if (match) {
      const dateVal = match[1];
      const daysVal = match[2];
      return `預定於 ${dateVal} 到期 (剩餘 ${daysVal} 天)`;
    }

    // Fallback keyword-by-keyword replacements
    return text
      .replace(/\bmiles\b/gi, unit)
      .replace(/\bmile\b/gi, unit)
      .replace(/Exceeded target of/gi, '已超過目標里程')
      .replace(/current:/gi, '當前實際：')
      .replace(/Due soon! Only/gi, '即將到期！僅剩')
      .replace(/remaining of/gi, '剩餘 / 總目標')
      .replace(/target/gi, '目標')
      .replace(/Safe:/gi, '安全：')
      .replace(/Overdue since/gi, '已逾期自')
      .replace(/days ago/gi, '天前')
      .replace(/Due in/gi, '限期')
      .replace(/days/gi, '天')
      .replace(/Upcoming on/gi, '即將於')
      .replace(/days left/gi, '天剩餘');
  }

  // English, replace miles with km
  return text
    .replace(/\bmiles\b/gi, 'km')
    .replace(/\bmile\b/gi, 'km')
    .replace(/\bodometer miles\b/gi, 'odometer km')
    .replace(/\btarget mileage\b/gi, 'target km');
}

/**
 * Dynamically converts manufacturer recommendation guidelines (e.g., oil changes)
 * into standard human-friendly rounded metric thresholds.
 */
export function convertMileageGuideline(milesValue: number, pref: 'imperial' | 'metric'): string {
  // Standard OEM mappings to preserve rounded clean intervals (e.g. 3,000 miles -> 5,000 km)
  switch (milesValue) {
    case 3000: return '5,000 km';
    case 5000: return '8,000 km';
    case 8000: return '13,000 km';
    case 15000: return '25,000 km';
    case 30000: return '50,000 km';
    case 20000: return '32,000 km';
    case 45000: return '72,000 km';
    default:
      return `${Math.round(milesValue * 1.60934).toLocaleString()} km`;
  }
}
